from datetime import datetime

from sqlalchemy import (
    Column,
    DateTime,
    ForeignKey,
    Integer,
    String,
)
from sqlalchemy.orm import relationship

from database.database import Base


class Student(Base):
    __tablename__ = "students"


    # PRIMARY KEY


    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )


    # ORGANIZATION

    #
    # organization_slug is NOT stored here.
    #
    # Authentication/application requests provide:
    #
    #     organization_slug
    #
    # The backend resolves it to:
    #
    #     organization_id
    #
    # Student stores only the foreign key.
    #


    organization_id = Column(
        Integer,
        ForeignKey("organizations.id"),
        nullable=False,
        index=True,
    )


    # LEGACY COMPATIBILITY

    #
    # Existing database still contains this field as NOT NULL.
    #
    # CampusFlow's canonical identity system uses:
    #
    #     application_number
    #     admission_number
    #     roll_number
    #
    # student_number is temporary compatibility only.


    student_number = Column(
        String(50),
        unique=True,
        nullable=False,
        index=True,
    )


    # USER ACCOUNT LINK

    #
    # NULL:
    #     Applicant has applied but does not have a registered
    #     Student/User account yet.
    #
    # NOT NULL:
    #     Student has been linked to a User account.
    #


    user_id = Column(
        Integer,
        ForeignKey("users.id"),
        nullable=True,
        index=True,
    )


    # APPLICANT AUTHENTICATION

    #
    # Used only during the applicant stage.
    #
    # Applicant login:
    #
    #     organization_slug
    #     +
    #     application_number
    #     +
    #     password
    #
    # The password is NEVER stored in plain text.
    #
    # Only the password hash is stored.
    #
    # Later OTP authentication can be added without changing
    # the overall authentication architecture.
    #


    applicant_password_hash = Column(
        String(255),
        nullable=True,
    )


    # PERSONAL INFORMATION


    full_name = Column(
        String(150),
        nullable=False,
    )

    email = Column(
        String(255),
        nullable=False,
        index=True,
    )

    phone = Column(
        String(30),
        nullable=True,
    )


    # ACADEMIC INFORMATION


    program = Column(
        String(150),
        nullable=False,
    )

    department = Column(
        String(150),
        nullable=True,
    )

    academic_year = Column(
        String(30),
        nullable=True,
    )

    semester = Column(
        String(30),
        nullable=True,
    )


    # GENERAL STUDENT STATUS


    status = Column(
        String(50),
        nullable=False,
        default="pending",
    )


    # CAMPUSFLOW IDENTIFIERS

    #
    # Application:
    #     APP-2026-00001
    #
    # Admission:
    #     ADM-2026-00001
    #
    # Roll:
    #     CSE26-001
    #
    # These identifiers are generated by their respective
    # workflows.
    #
    # IMPORTANT:
    #
    # Application numbers are logically organization-scoped.
    #
    # The database uniqueness constraint will be updated through
    # a migration to:
    #
    #     UNIQUE(organization_id, application_number)
    #


    application_number = Column(
        String(50),
        nullable=True,
        index=True,
    )

    admission_number = Column(
        String(50),
        unique=True,
        nullable=True,
        index=True,
    )

    roll_number = Column(
        String(50),
        unique=True,
        nullable=True,
        index=True,
    )


    # ADMISSION STATE


    admission_status = Column(
        String(50),
        nullable=False,
        default="draft",
    )


    # TIMESTAMPS


    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    updated_at = Column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False,
    )


    # RELATIONSHIPS


    organization = relationship(
        "Organization",
        back_populates="students",
    )

    admissions = relationship(
        "Admission",
        back_populates="student",
        cascade="all, delete-orphan",
    )

    onboarding_tasks = relationship(
        "OnboardingTask",
        back_populates="student",
        cascade="all, delete-orphan",
    )

    user = relationship(
        "User",
        back_populates="student_profile",
        uselist=False,
    )

    documents = relationship(
        "StudentDocument",
        back_populates="student",
        cascade="all, delete-orphan",
    )